from scipy import *
from numpy import *
from pylab import *
import matplotlib.pyplot as pyplot

a = genfromtxt('a_evol.txt')
phi = genfromtxt('phi_a.txt')
phiprime = genfromtxt('phiprime_a.txt')
hubble = genfromtxt('hubble.txt')
weff = genfromtxt('weff.txt')
weff_new = genfromtxt('eft_new_weff.txt')
weff_new_prime = genfromtxt('eft_new_weffprime.txt')
eft_c = genfromtxt('eft_c_des.txt')
eft_c_dot = genfromtxt('eft_cdot_des.txt')
eft_lamda = genfromtxt('eft_lambda_des.txt')
eft_lamda_dot = genfromtxt('eft_lambdadot_des.txt')
odef = genfromtxt('omegade.txt')
wbd = 75.0
phi0 = (2.0*wbd+4.0)/(2.0*wbd+3.0)
figure(1)
plot(a,phi,label = 'numerical')
plot(a,phi0*a**(1.0/(1.0+wbd)),label = 'attractor')
pyplot.xscale('log')
xlim([1.0e-7,1.0])
xlabel('a',fontsize=15)
ylabel(r'$\phi$',fontsize=15)
legend(loc=0)

figure(2)
plot(a,phiprime,label = 'numerical')
plot(a,phi0/(1.0+wbd)*a**(1.0/(1.0+wbd)),label = 'attractor')
pyplot.xscale('log')
xlim([1.0e-7,1.0])
xlabel('a',fontsize=15)
ylabel(r'$\phi^{\prime}$',fontsize=15)
legend(loc=0)

figure(3)
plot(a,hubble)#-hubble_lamda)/hubble_lamda)
pyplot.xscale('log')
#pyplot.yscale('log')
xlim([1.0e-1,1.0])
ylim([60,150.0])
xlabel('a',fontsize=15)
ylabel(r'$H(a)$',fontsize=15)

figure(4)
plot(a,weff,label = "Traditional")
plot(a,weff_new,label = "EFT")
pyplot.xscale('log')
xlim([1.0e-8,1.0])
ylim([-1.2,-0.3])
xlabel('a',fontsize=15)
ylabel(r'$w_{\rm{eff}}$',fontsize=15)

figure(5)
plot(a,odef)
pyplot.xscale('log')
xlim([1.0e-3,1.0])
ylim([0.0,1.0])
xlabel('a',fontsize=15)
ylabel(r'$\Omega_{\rm{de}}$',fontsize=15)

figure(6)
plot(a,weff*odef)
pyplot.xscale('log')
xlim([1.0e-3,1.0])
ylim([0.0,-1.0])
xlabel('a',fontsize=15)
ylabel(r'$p_{\rm{de}}$',fontsize=15)

figure(7)
plot(a,weff_new_prime)
pyplot.xscale('log')
xlim([1.0e-8,1.0])
xlabel('a',fontsize=15)
ylabel(r'$w_{\rm{eff}}^{\prime}$',fontsize=15)

figure(8)
plot(a,eft_c_dot,label = r'$\rm{EFT}_{C}$')
plot(a,eft_lamda_dot,label = r'$\rm{EFT}_{\Lambda}$')
pyplot.xscale('log')
xlim([1.0e-8,1.0])
xlabel('a',fontsize=15)
legend(loc=0)


show()
