figure(3)
plot(a,hubble)#-hubble_lamda)/hubble_lamda)
pyplot.xscale('log')
#pyplot.yscale('log')
xlim([1.0e-1,1.0])
ylim([1.0,20.0])
xlabel('a',fontsize=15)
ylabel(r'$H(a)$',fontsize=15)

figure(4)
plot(a,weff)
pyplot.xscale('log')
xlim([1.0e-3,1.0])
ylim([-1.2,-0.3])
xlabel('a',fontsize=15)
ylabel(r'$w_{\rm{eff}}$',fontsize=15)

figure(5)
plot(a,odef)
pyplot.xscale('log')
xlim([1.0e-3,1.0])
ylim([0.0,1.0])
xlabel('a',fontsize=15)
ylabel(r'$\Omega_{\rm{de}}$',fontsize=15)

figure(6)
plot(a,weff*odef)
pyplot.xscale('log')
xlim([1.0e-3,1.0])
ylim([0.0,1.0])
xlabel('a',fontsize=15)
ylabel(r'$p_{\rm{de}}$',fontsize=15)
